title: Chinagorom Odo
description: Data Analyst & Market Researcher building retail and tech-driven solutions in Africa
show_downloads: false
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme 
